# Generated by Django 2.1.4 on 2018-12-20 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myinfo', '0002_myinfo_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myinfo',
            old_name='amount',
            new_name='amount_reg',
        ),
    ]
