# Generated by Django 2.1.4 on 2018-12-26 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myinfo', '0003_auto_20181220_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade_info',
            fields=[
                ('inx', models.AutoField(primary_key=True, serialize=False)),
                ('gubun', models.CharField(blank=True, max_length=10)),
                ('value_reg', models.CharField(blank=True, max_length=100, null=True)),
                ('date_reg', models.DateTimeField(blank=True, null=True)),
                ('desc_reg', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
