# Generated by Django 2.1.4 on 2018-12-26 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myinfo', '0006_sr_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='sr_info',
            name='value_reg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
