# Generated by Django 2.1.4 on 2018-12-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myinfo', '0007_sr_info_value_reg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sr_info',
            name='amount_reg',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sr_info',
            name='send_money',
            field=models.FloatField(default=0),
        ),
    ]
