# Generated by Django 2.1.4 on 2018-12-28 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myinfo', '0008_auto_20181226_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='sr_info',
            name='status_reg',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
