# Generated by Django 2.1.4 on 2018-12-28 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myinfo', '0009_sr_info_status_reg'),
    ]

    operations = [
        migrations.AddField(
            model_name='sr_info',
            name='gubun_reg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
