# Generated by Django 2.1.4 on 2019-01-04 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myinfo', '0010_sr_info_gubun_reg'),
    ]

    operations = [
        migrations.AddField(
            model_name='myinfo',
            name='myaccount_reg',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
