# Generated by Django 2.1.4 on 2019-01-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myinfo', '0011_myinfo_myaccount_reg'),
    ]

    operations = [
        migrations.AddField(
            model_name='myinfo',
            name='myaccount_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
